channels:
- psi4
- defaults
- reinimaurer1
- conda-forge
- anaconda
- pyqc
- rdkit
- iwatobipen
dependencies:
- psi4
- psi4-rt
- v2rdm_casscf
- python
- ipython=6.1.0
- nbconvert=5.6.1
- setuptools
- six
- gcp
- dbus
- glib
- gmp=6.1.0
- ipykernel=4.6.1
- libgcc=5.2.0
- libgfortran=3.0.0
- mkl=2017.0.1
- bleach=1.5.0
- expat=2.1.0
- gst-plugins-base=1.8.0
- path.py=10.3.1
- gstreamer=1.8.0
- clyent=1.2.2
- idna=2.5
- matplotlib
- numpy=1.12.1
- scipy
- bokeh=0.12.7
- ipywidgets
- rdkit
- qmp
- ase
- debtcollector
- psikit
