name: PX919env
channels:
- psi4
- rdkit
- iwatobipen
- conda-forge
- defaults
dependencies:
- ipykernel
- matplotlib
- numpy
- scipy
- bokeh
- ipywidgets
- rdkit
- mdtraj
- nglview
- ase
- psi4
- debtcollector
- psikit
- py3dmol
