channels:
- psi4
- defaults
- reinimaurer1
- conda-forge
dependencies:
- python=3.6
- ipython=6.1.0
- gcp=2.0.1
- dbus=1.10.20
- glib=2.50.2
- gmp=6.1.0
- ipykernel=4.6.1
- libgcc=5.2.0
- libgfortran=3.0.0
- mkl=2017.0.1
- psi4
- psi4-rt
- matplotlib
- numpy
- scipy
- bokeh
- ipywidgets
- qmp
- ase
