name: PX919env
channels:
- psi4
- defaults
- reinimaurer1
- conda-forge
- rdkit
- iwatobipen
dependencies:
- psi4
- setuptools
- six
- gcp
- dbus
- glib
- ipykernel
- matplotlib
- numpy
- scipy
- bokeh
- ipywidgets
- rdkit
- qmp
- ase
- debtcollector
- mdtraj
- nglview
- psikit
